exclude: [CNAME, Gemfile, Gemfile.lock, README.md, Makefile]
timezone: Europe/Paris
markdown: kramdown
highlighter: pygments
permalink: /:year/:month/:day/:title/
excerpt_separator: ""

google_analytics_id: UA-68404966-2

repository: https://github.com/MonsieurV/monsieurv.github.io

name: Simple, distributed software
description: Blog written by YtoTech members about complex and distributed software made simple.
url: http://blog.ytotech.com

sass:
    style: compressed

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"
      author: monsieurv
