plugins:
  - jekyll-feed
exclude: [CNAME, Gemfile, Gemfile.lock, README.md, Makefile]
# TODO Be universal: UTC time.
timezone: Europe/Paris
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
repository: https://github.com/MonsieurV/monsieurv.github.io


name: YtoTech SDS blog
description: Blog by YtoTech members on complex and distributed software - made simple and fun!
url: https://blog.ytotech.com
author:
  name: YtoTech members
  email: hello@ytotech.com
  uri: https://www.ytotech.com/

sass:
  style: compressed

exclude: [vendor]
