exclude: [CNAME, Gemfile, Gemfile.lock, README.md]
timezone: Europe/Paris
markdown: kramdown
highlighter: pygments
permalink: /:year/:month/:day/:title/
excerpt_separator: ""

google_analytics_id: UA-68404966-2

repository: https://github.com/MonsieurV/monsieurv.github.io

name: YtoTech Blog • Complex and distributed computing
description: YtoTech blog about complex and distributed pieces of software.
url: http://blog.ytotech.com

sass:
    style: compressed

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: ""
