gems:
  - jekyll-feed
exclude: [CNAME, Gemfile, Gemfile.lock, README.md, Makefile]
timezone: Europe/Paris
markdown: kramdown
highlighter: pygments
permalink: /:year/:month/:day/:title/
google_analytics_id: UA-68404966-2
repository: https://github.com/MonsieurV/monsieurv.github.io


name: Simple, distributed software
description: Blog written by YtoTech members about complex and distributed software hopefully made simple and fun.
url: http://blog.ytotech.com
author:
    name: Yto Tech members
    email: contact@ytotech.com
    uri: http://www.ytotech.com/people/

sass:
    style: compressed
